### ISSUE TITLE
MetaMask no longer injects web3

### ISSUE THREAD

**Issue by javany** [ProxeusApp/proxeus-core#234] opened 2021-11-07 18:21 UTC
### web3 Provider Breaking Changes
to see the breaking changes and Provider Migration Guide: check the following link:
[Attention MetaMask Users](https://docs.metamask.io/guide/provider-migration.html#table-of-contents)

because of these breaking changes, signing in with Metamask is not possible.

**Comment by loleg** [comment] 2021-11-29 10:13
Duplicate of #203 and #226

**Closed** 2021-12-04 14:32 UTC
Labels: bug, dependencies
