### ISSUE TITLE
Form Radio Button status and values can be out of synch

### ISSUE THREAD

**Issue by stefanvogel65** [ProxeusApp/proxeus-core#200] opened 2020-12-22 16:57 UTC
### Subject of the issue
When using radio buttons on forms in the workflows, the status of the radio button widget and the actual value can be out of synch, e.g. a radio button looks to be set to a specific selection although the variable associated with the radio button is not set. Under some circumstances, similar inconsistencies appear for drop-down lists, however more rarely.

### Your environment
Tried on Proxeus core on RHEL v 7 and with different browsers (Firefox, Chrome).

### Steps to reproduce

Import the testing workflow to Proxeus and insert the ODT template to the Proxeus template “Test Template” and run it.
The testing workflow’s key form is the “Test-Input” Form where two radio buttons and two drop downs are inserted, one of each with default values set and one with no default value. There are three ways to check on the actual status of the variables behind the radio buttons and drop downs:

1.	Headline components that only appear when certain values are set
2.	A template that lists the variable settings in the workflow
3.	A conditional node that branches to one of two static forms depending on the value of DropDown1

Start the workflow and compare the elements on the form with what the rendered template shows. Proceed to the next form to check whether the variable of RadioButton2 is actually set to “1st value”. Change settings of the drop downs and radio buttons on the form and compare with the rendered template.

When you complete a workflow instance and start a new one, the behavior is slightly changed. Also, there might be a different initial form status when you start a workflow instance as another user.

Depending on the constellation (new/existing user, 1st or second instance of a workflow, …) the behavior can be different. E.g. it might be that the conditional components on the form appear as expected, however the variables in the rendered document are not set.

See attached word document for screenshots from some testing scenarios.

### Expected behavior

The status of the radio buttons and drop downs as they appear on the form should always be in synch 

*  with the conditional elements shown on the form, 
*  with what the values in the rendered document are and 
*  with what is evaluated in the conditional node of the workflow.

### Actual behavior

There are constellations where the drop downs and / or radio buttons appear to be set to a specific value, but these values 

*  are not displayed in the rendered document, 
*  do not result in the corresponding display of the conditional form components, and 
*   are not evaluated as they should in the conditional nodes in the workflow.

In particular, on startup of the first workflow instance, RadioButton1 looks as if is set to “1st value” (as it should, as this is the default setting), however neither the conditional Headline component is displayed, nor the corresponding value in the rendered form is set, nor the conditional node leads to the expected next form “Test Output”.

Find the following in attached zip file [Test-Artefacts.zip](https://github.com/ProxeusApp/proxeus-core/files/5731080/Test-Artefacts.zip)

* Exported Proxeus Workflow: Proxeus-Workflow_08a844a4-633a-4b95-afa9-be23e584cd4c_22-12-2020_17-51.db
* Details of the scenarios tested with screenshots: Testing Radio Buttons and Drop Down Behavior.docx
* Template ODT file to use in the corresponding Proxeus template: Test-Template.odt

**Comment by loleg** [comment] 2020-12-23 15:16
@stefanvogel65 thank you very much for this detailed and clear problem description. It would be great if you could add a screenshot as well as the version of the browser(s) you're seeing this in. 

ZIP files with binaries, however, are generally discouraged in bug reports, as they can be a source of viruses. I am holding on to a copy of the files myself, and will be happy to provide it to a developer on request.

We will look into this and try to analyse the cause as soon as we can.

**Comment by stefanvogel65** [comment] 2021-01-04 10:34
@loleg thank you for looking into this.

On the ZIP attachment: I choose a zip as at least the workflow export (Proxeus *.db file) cannot be attached otherwise.

The browsers I tried are:

* Firefox 84.0.1 (64-bit)
* Google Chrome 87.0.4280.88 (Official Build) (64-bit)

I put the content of the Word attachment here for convenience. Please let me know in case you need something else.

# Testing Radio Buttons and Drop Down Behavior

Stefan Vogel, 22 Dec. 2020

## Test Workflow

![image](https://user-images.githubusercontent.com/35991100/103525423-796e0a80-4e7f-11eb-8437-76df20f84cfe.png)

Get the details from Proxeus-Workflow_08a844a4-633a-4b95-afa9-be23e584cd4c_22-12-2020_17-51.db in the ZIP attachment.

## Test scenario 1, fresh start
### Initial screen
![image](https://user-images.githubusercontent.com/35991100/103525556-b5a16b00-4e7f-11eb-8c30-2947a76b1fe9.png)

### Issues
* Conditional Block for RadioButton2 = “1st Value” is not displayed on form.
* Values in rendered document are not set (empty), even though RadioButton1 looks as if it is set to “1st Value”. DropDown1 is supposed to show value “empty” for “Select…”:

![image](https://user-images.githubusercontent.com/35991100/103525651-dbc70b00-4e7f-11eb-9332-b7627bb4c9ea.png)
 
## Test scenario 2, 2nd run, all correct
DropDowns and RadioButtons are selected as shown, conditional blocks all appear as they should.

![image](https://user-images.githubusercontent.com/35991100/103525745-0b761300-4e80-11eb-88b8-68c1dbd26706.png)

Rendered form is filled correctly:

![image](https://user-images.githubusercontent.com/35991100/103525760-1630a800-4e80-11eb-9696-eea8e3c29616.png)
 
Proceeding to the next form: Conditional node performs correctly:

![image](https://user-images.githubusercontent.com/35991100/103525807-26e11e00-4e80-11eb-981e-773834a1587e.png)
 
## Test Scenario 4, restart after document delete
Form initialized as expected, however, conditional Block for RadioButton2, 1st Value is hidden.

![image](https://user-images.githubusercontent.com/35991100/103525842-352f3a00-4e80-11eb-9585-4bb4493ec58b.png)

Rendered Doc does not show value for RadioButton2, in contrast to what is expected.

![image](https://user-images.githubusercontent.com/35991100/103525872-3fe9cf00-4e80-11eb-9a82-04f64e69ad5d.png)
 
Navigating to the next form shows that RadioButton2 value is not set to “1st Value”:

![image](https://user-images.githubusercontent.com/35991100/103525920-4e37eb00-4e80-11eb-9bf3-3c085f7f9fe8.png)

## Test Scenario 5, Logged in with different user (Metamask)

Create new document from same workflow. Values seem to be inherited from pending draft from other user, conditional Blocks on form look consistent to the values pre-selected:

![image](https://user-images.githubusercontent.com/35991100/103525961-5db73400-4e80-11eb-8710-d0d36562d1f0.png)
 
However, rendering does not show any radio button or drop down value set:
 
![image](https://user-images.githubusercontent.com/35991100/103525987-690a5f80-4e80-11eb-90be-71072e276e37.png)

## Test Scenario 6, Another fresh start
Started a new document, form initializes like this:

![image](https://user-images.githubusercontent.com/35991100/103526011-74f62180-4e80-11eb-81ec-cdd0f533da5b.png)

Observation:
1.	RadioButton2 set to default value “1st Value”, as expected.
2.	Conditional Block for RadioButton2 for “1st value” is hidden
3.	Drop downs set to 1st value, even though DropDown1 expected to be not set.
4.	Rendering does not show any value for Radio Buttons or Drop Downs:

![image](https://user-images.githubusercontent.com/35991100/103526025-7e7f8980-4e80-11eb-904d-32a775a4e565.png)

**Comment by loleg** [comment] 2024-04-24 07:43
We started a new investigation to this issue, since we had a better idea of how to address it. A fix is in the works.

**Comment by slavas490** [comment] 2024-04-26 14:09
done

**Closed by slavas490** 2024-04-26 14:09 UTC
Labels: bug, bounty

**Comment by loleg** [comment] 2024-05-21 07:47
The fix has now been [released](https://github.com/ProxeusApp/proxeus-core/releases/tag/v1.6.4)
